### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by sunsunshark** [HJ-harry/DiffusionMBIR#9]
When I started training using my data，such an error occurred
data:
  centered: false
  dataset: AAPM
  image_size: 256
  is_complex: false
  is_multi: false
  num_channels: 1
  random_flip: true
  root: /media/sun/tomo/AAPM_data/256
  uniform_dequantization: false
device: !!python/object/apply:torch.device
- cuda
- 0
eval:
  batch_size: 8
  begin_ckpt: 50
  bpd_dataset: test
  enable_bpd: false
  enable_loss: true
  enable_sampling: true
  end_ckpt: 96
  num_samples: 50000
model:
  attention_type: ddpm
  attn_resolutions: !!python/tuple
  - 16
  beta_max: 20.0
  beta_min: 0.1
  ch_mult: !!python/tuple
  - 1
  - 2
  - 2
  - 2
  conditional: true
  conv_size: 3
  dropout: 0.0
  ema_rate: 0.999
  embedding_type: fourier
  fir: true
  fir_kernel:
  - 1
  - 3
  - 3
  - 1
  fourier_scale: 16
  init_scale: 0.0
  name: ncsnpp
  nf: 128
  nonlinearity: swish
  normalization: GroupNorm
  num_res_blocks: 4
  num_scales: 2000
  progressive: none
  progressive_combine: sum
  progressive_input: residual
  resamp_with_conv: true
  resblock_type: biggan
  scale_by_sigma: true
  sigma_max: 378
  sigma_min: 0.01
  skip_rescale: true
optim:
  beta1: 0.9
  eps: 1.0e-08
  grad_clip: 1.0
  lr: 0.0002
  optimizer: Adam
  warmup: 5000
  weight_decay: 0
sampling:
  corrector: langevin
  method: pc
  n_steps_each: 1
  noise_removal: true
  predictor: reverse_diffusion
  probability_flow: false
  snr: 0.075
seed: 42
training:
  batch_size: 1
  continuous: true
  epochs: 1000
  eval_freq: 100
  likelihood_weighting: false
  log_freq: 25
  reduce_mean: false
  sde: vesde
  snapshot_freq: 50000
  snapshot_freq_for_preemption: 5000
  snapshot_sampling: true

Traceback (most recent call last):
  File "E:\py2\DiffusionMBIR-main\main.py", line 71, in <module>
    app.run(main)
  File "D:\Anaconda\envs\diffusion-mbir\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "D:\Anaconda\envs\diffusion-mbir\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "E:\py2\DiffusionMBIR-main\main.py", line 62, in main
    run_lib.train(FLAGS.config, FLAGS.workdir)
  File "E:\py2\DiffusionMBIR-main\run_lib.py", line 82, in train
    state = restore_checkpoint(checkpoint_meta_dir, state, config.device)
  File "E:\py2\DiffusionMBIR-main\utils.py", line 38, in restore_checkpoint
    loaded_state = torch.load(ckpt_dir, map_location=device)
  File "D:\Anaconda\envs\diffusion-mbir\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Anaconda\envs\diffusion-mbir\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Anaconda\envs\diffusion-mbir\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'workdir\\AAPM256\\checkpoints-meta'

Process finished with exit code 1

How can I solve the problem?

**Comment by LiZhou-1004** [comment]
> When I started training using my data，such an error occurred data: centered: false dataset: AAPM image_size: 256 is_complex: false is_multi: false num_channels: 1 random_flip: true root: /media/sun/tomo/AAPM_data/256 uniform_dequantization: false device: !!python/object/apply:torch.device
> 
> * cuda
> * 0
>   eval:
>   batch_size: 8
>   begin_ckpt: 50
>   bpd_dataset: test
>   enable_bpd: false
>   enable_loss: true
>   enable_sampling: true
>   end_ckpt: 96
>   num_samples: 50000
>   model:
>   attention_type: ddpm
>   attn_resolutions: !!python/tuple
>   
>   * 16
>     beta_max: 20.0
>     beta_min: 0.1
>     ch_mult: !!python/tuple
>   * 1
>   * 2
>   * 2
>   * 2
>     conditional: true
>     conv_size: 3
>     dropout: 0.0
>     ema_rate: 0.999
>     embedding_type: fourier
>     fir: true
>     fir_kernel:
>   * 1
>   * 3
>   * 3
>   * 1
>     fourier_scale: 16
>     init_scale: 0.0
>     name: ncsnpp
>     nf: 128
>     nonlinearity: swish
>     normalization: GroupNorm
>     num_res_blocks: 4
>     num_scales: 2000
>     progressive: none
>     progressive_combine: sum
>     progressive_input: residual
>     resamp_with_conv: true
>     resblock_type: biggan
>     scale_by_sigma: true
>     sigma_max: 378
>     sigma_min: 0.01
>     skip_rescale: true
>     optim:
>     beta1: 0.9
>     eps: 1.0e-08
>     grad_clip: 1.0
>     lr: 0.0002
>     optimizer: Adam
>     warmup: 5000
>     weight_decay: 0
>     sampling:
>     corrector: langevin
>     method: pc
>     n_steps_each: 1
>     noise_removal: true
>     predictor: reverse_diffusion
>     probability_flow: false
>     snr: 0.075
>     seed: 42
>     training:
>     batch_size: 1
>     continuous: true
>     epochs: 1000
>     eval_freq: 100
>     likelihood_weighting: false
>     log_freq: 25
>     reduce_mean: false
>     sde: vesde
>     snapshot_freq: 50000
>     snapshot_freq_for_preemption: 5000
>     snapshot_sampling: true
> 
> Traceback (most recent call last): File "E:\py2\DiffusionMBIR-main\main.py", line 71, in app.run(main) File "D:\Anaconda\envs\diffusion-mbir\lib\site-packages\absl\app.py", line 312, in run _run_main(main, args) File "D:\Anaconda\envs\diffusion-mbir\lib\site-packages\absl\app.py", line 258, in _run_main sys.exit(main(argv)) File "E:\py2\DiffusionMBIR-main\main.py", line 62, in main run_lib.train(FLAGS.config, FLAGS.workdir) File "E:\py2\DiffusionMBIR-main\run_lib.py", line 82, in train state = restore_checkpoint(checkpoint_meta_dir, state, config.device) File "E:\py2\DiffusionMBIR-main\utils.py", line 38, in restore_checkpoint loaded_state = torch.load(ckpt_dir, map_location=device) File "D:\Anaconda\envs\diffusion-mbir\lib\site-packages\torch\serialization.py", line 594, in load with _open_file_like(f, 'rb') as opened_file: File "D:\Anaconda\envs\diffusion-mbir\lib\site-packages\torch\serialization.py", line 230, in _open_file_like return _open_file(name_or_buffer, mode) File "D:\Anaconda\envs\diffusion-mbir\lib\site-packages\torch\serialization.py", line 211, in **init** super(_open_file, self).**init**(open(name, mode)) PermissionError: [Errno 13] Permission denied: 'workdir\AAPM256\checkpoints-meta'
> 
> Process finished with exit code 1
> 
> How can I solve the problem?

Hello Sunshark, I have also encountered the same problem as you. Have you solved this problem? May I ask for your advice on a solution?

**Comment by BanyeDguduyue** [comment]
hello ，do you have data？
